- docs/README.md
- docs/arch/folder.md
- readme파일 경로 중 빠진 부분들을 넣었습니다.
- 참고사항/의논사항:
> fix: md 파일 경로 및 단어 수정

- .gitignore
- _tools/README.md
- _tools/merge_docs.sh
- 인공지능에게 던져주기 위한 1개의 병합문서를 생성해줍니다.
- #3
> [Util] 문서 병합 스크립트 유틸 구현

- .github/ISSUE_TEMPLATE/docs_template.md
- .github/workflows/pr-labeler.yml
> [utils] 자동화 테스트

- docs/README.md
- readme 파일중 경로 삭제 후 추가했습니다.
- 참고사항/의논사항:
> docs: readme 파일 추가 및 수정

- .github/workflows/add-to-project.yml
- .github/workflows/pr-labeler.yml
> [utils]gitHub 자동화 테스트

- .gitignore
- analysis_options.yaml
- lib/main.dart
- pubspec.yaml
- test/auth/data/data_source/mock_auth_data_source_test.dart
- test/auth/presentation/login_notifier_test.dart
> init: init devlink-mobile-app

- lib/auth/data/data_source/auth_data_source.dart
- lib/auth/data/data_source/mock_auth_data_source.dart
- lib/auth/data/dto/user_dto.dart
- lib/auth/data/mapper/user_mapper.dart
- lib/auth/data/repository_impl/auth_repository_impl.dart
- lib/auth/domain/model/user.dart
- lib/auth/domain/repository/auth_repository.dart
- lib/auth/domain/usecase/login_use_case.dart
- lib/auth/domain/usecase/mock_login_user_case.dart
- lib/auth/module/auth_di.dart
- lib/auth/presentation/login_notifier.dart
- lib/auth/presentation/login_state.dart
- lib/core/result/result.dart
- test/auth/presentation/login_notifier_test.dart
> [feat] auth 비즈니스 로직 구현

- _tools/merge_docs.sh
> [docs] 문서 병합 유틸 수정 (생성날짜 기록)

- lib/auth/domain/model/member.dart
- lib/auth/domain/usecase/get_member_by_id_use_case.dart
- Member 모델 생성
- getMemberByIdUseCase 생성
- 관련 이슈: #54 
- 참고사항/의논사항: 모델 필드 제대로 생성했는지, useCase작성 잘 했는지.
> [feat] Member모델 생성 및 getMemberByIdUseCase 생성

- lib/community/data/data_source/mock_post_data_source_impl.dart
- lib/community/data/data_source/post_data_source.dart
- lib/community/data/mapper/commnet_mapper.dart
- lib/community/data/repository_impl/post_repository_impl.dart
- lib/community/domain/model/hash_tag.dart
- lib/community/domain/model/like.dart
- lib/community/domain/model/post.dart
- lib/community/domain/repository/post_repository.dart
- lib/community/domain/usecase/create_comment_use_case.dart
- lib/community/domain/usecase/fetch_comments_use_case.dart
- lib/community/domain/usecase/fetch_post_detail_use_case.dart
- lib/community/domain/usecase/toggle_bookmark_use_case.dart
- lib/community/domain/usecase/toggle_like_use_case.dart
- lib/community/module/community_di.dart
- lib/community/module/community_router.dart
- lib/community/presentation/community_detail/community_detail_action.dart
- lib/community/presentation/community_detail/community_detail_notifier.dart
- lib/community/presentation/community_detail/community_detail_screen.dart
- lib/community/presentation/community_detail/community_detail_screen_root.dart
- lib/community/presentation/community_detail/community_detail_state.dart
- lib/community/presentation/community_detail/component/comment_item.dart
- lib/community/presentation/community_list/community_list_state.dart
> [feat] Community Detail Screen 

- lib/group/presentation/group_create/group_create_screen.dart
- (여기에 변경 또는 추가한 주요 사항을 간략히 적어주세요)
- 참고사항/의논사항:
> 지금 머지합니다. 긴급수정

- lib/community/domain/usecase/create_comment_use_case.dart
- lib/community/domain/usecase/create_post_use_case.dart
- lib/community/domain/usecase/fetch_comments_use_case.dart
- lib/community/domain/usecase/fetch_post_detail_use_case.dart
- lib/community/domain/usecase/load_post_list_use_case.dart
- lib/community/domain/usecase/toggle_bookmark_use_case.dart
- lib/community/domain/usecase/toggle_like_use_case.dart
- lib/community/presentation/community_detail/community_detail_notifier.dart
- lib/community/presentation/community_detail/community_detail_screen.dart
- lib/community/presentation/community_list/community_list_notifier.dart
- lib/community/presentation/community_list/community_list_screen.dart
- lib/community/presentation/community_list/community_list_state.dart
- lib/community/presentation/community_write/community_write_notifier.dart
- lib/community/presentation/components/post_list_item.dart
> [feat] 클로드로 코드 리팩토링

- lib/community/domain/usecase/create_comment_use_case.dart
- lib/community/domain/usecase/create_post_use_case.dart
- lib/community/domain/usecase/fetch_comments_use_case.dart
- lib/community/domain/usecase/fetch_post_detail_use_case.dart
- lib/community/domain/usecase/load_post_list_use_case.dart
- lib/community/domain/usecase/toggle_bookmark_use_case.dart
- lib/community/domain/usecase/toggle_like_use_case.dart
- lib/community/presentation/community_detail/community_detail_notifier.dart
- lib/community/presentation/community_detail/community_detail_screen.dart
- lib/community/presentation/community_list/community_list_notifier.dart
- lib/community/presentation/community_list/community_list_screen.dart
- lib/community/presentation/community_list/community_list_state.dart
- lib/community/presentation/community_write/community_write_notifier.dart
- lib/community/presentation/components/post_list_item.dart
- lib/core/component/custom_alert_dialog.dart
- lib/core/component/navigation_bar.dart
- lib/core/navigation_bar/navigation_bar.dart
- lib/edit_intro/presentation/screens/edit_intro_screen.dart
- lib/intro/presentation/intro_screen_root.dart
- lib/setting/presentation/settings_screen.dart
- lib/setting/presentation/settings_screen_root.dart
- (여기에 변경 또는 추가한 주요 사항을 간략히 적어주세요)
- 참고사항/의논사항:
> [sub_feat] 프로필 수정 및 네비게이션바 구현(#105)

- lib/auth/presentation/component/custom_text_field.dart
- lib/auth/presentation/forgot_password/forgot_password_screen.dart
- lib/auth/presentation/login/login_screen.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/auth/presentation/signup/signup_state.dart
- lib/auth/presentation/terms/terms_screen.dart
- [refac] 로그인 화면 디자인 및 리팩토링 (#111)
- 관련 이슈: #46 
- 참고사항/의논사항:
> [refac] 로그인 화면 디자인 및 리팩토링 (#111)

- lib/auth/presentation/component/custom_text_field.dart
- lib/auth/presentation/forgot_password/forgot_password_screen.dart
- lib/auth/presentation/login/login_screen.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/auth/presentation/signup/signup_state.dart
- lib/auth/presentation/terms/terms_screen.dart
- 로그인 기능 전체 리펙토링 및 디자인 수정.
- 
- 참고사항/의논사항:
> [refac] 로그인 기능 전체 리팩토링 완료 (#46)

- lib/auth/module/auth_di.dart
- lib/community/module/community_router.dart
- lib/core/router/app_router.dart
- lib/group/module/group_di.dart
- lib/main.dart
- 여러분 파일병합 했습니다.
- 그룹 다이얼로그에서 오류가 있습니다. 
- 관련 이슈: #128
> [feat] Router 병합 및 버텀시트

- docs/README.md
- docs/logic/firebase_model.md
-  logic/firebase_model.md 추가
- 관련 이슈: #137
> [docs] logic/firebase_model.md 추가

- lib/core/router/app_router.dart
> fix(profile): router 오류

- ios/Podfile
- ios/Runner.xcodeproj/project.pbxproj
- ios/Podfile 13 버전 수정 후 빌드
- 관련 이슈: #143
> [fix] iOS 설정 변경

- lib/auth/presentation/forgot_password/forgot_password_screen.dart
- lib/auth/presentation/login/login_screen.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/auth/presentation/terms/terms_screen.dart
- lib/auth/presentation/terms/terms_screen_root.dart
- auth 모든 화면 오버플로우 버그 해결
- 로그인, 약관, 비밀번호 재설정, 회원가입
> [fix] auth 모든 화면 오버플로우 버그 해결

- lib/core/styles/app_theme.dart
- lib/main.dart
> [fix] app 전체 테마 설정 완료 / main 수정 완료 (#173)

- lib/auth/presentation/component/custom_text_field.dart
- lib/auth/presentation/login/login_notifier.dart
- lib/auth/presentation/login/login_screen_root.dart
- 비밀번호 확인 버튼 추가했습니다.
- 회원가입시 버그리포트를 추가했습니다.
- 
- 관련 이슈: 
- 참고사항/의논사항:
> [bug] bug report 추가, 비밀번호 확인 버튼 추가

- lib/group/data/data_source/mock_group_data_source_impl.dart
- lib/group/domain/usecase/get_current_member_use_case.dart
- lib/group/module/group_di.dart
- lib/group/presentation/group_list/group_list_action.dart
- lib/group/presentation/group_list/group_list_notifier.dart
- lib/group/presentation/group_list/group_list_screen.dart
- lib/group/presentation/group_list/group_list_screen_root.dart
- lib/group/presentation/group_list/group_list_state.dart
- lib/group/presentation/group_list_item.dart
- lib/group/presentation/group_search/group_search_action.dart
- lib/group/presentation/group_search/group_search_notifier.dart
- lib/group/presentation/group_search/group_search_screen.dart
- lib/group/presentation/group_search/group_search_screen_root.dart
- lib/group/presentation/group_search/group_search_state.dart
- pubspec.yaml
- 그룹 목록과 관련된 이슈를 모두 수정하였습니다.
- 관련 이슈: #150 #162
> [bug] 그룹목록 관련 이슈해결

- lib/core/router/app_router.dart
- lib/core/styles/app_theme.dart
- lib/home/data/data_source/home_data_source.dart
- lib/home/data/data_source/mock_home_data_source_impl.dart
- lib/home/data/repository_impl/home_repository_impl.dart
- lib/home/domain/model/notice.dart
- lib/home/domain/repository/home_repository.dart
- lib/home/domain/usecase/get_notices_use_case.dart
- lib/home/domain/usecase/get_popular_posts_use_case.dart
- lib/home/domain/usecase/get_user_groups_use_case.dart
- lib/home/module/home_di.dart
- lib/home/presentation/component/group_section.dart
- lib/home/presentation/component/notice_section.dart
- lib/home/presentation/component/popular_post_section.dart
- lib/home/presentation/home_action.dart
- lib/home/presentation/home_notifier.dart
- lib/home/presentation/home_screen.dart
- lib/home/presentation/home_screen_root.dart
- lib/home/presentation/home_state.dart
> [feat] home mock 구현

- lib/community/presentation/community_list/community_list_screen.dart
- lib/group/presentation/group_list/group_list_screen.dart
- lib/home/data/data_source/mock_home_data_source_impl.dart
- lib/home/presentation/home_screen copy.dart
> [refactor] home 화면 UI 수정

- lib/community/data/data_source/mock_post_data_source_impl.dart
- lib/community/module/community_di.dart
- lib/core/router/app_router.dart
- lib/home/presentation/component/popular_post_section.dart
- home 화면 인기 게시글 불러오기를 해결하였습니다.
- 관련 이슈: #199
> [bug] 인기 게시글 불러오기 이슈 해결

- lib/core/component/gradient_app_bar.dart
- lib/core/component/search_bar_component.dart
- lib/group/presentation/group_create/group_create_screen.dart
- lib/group/presentation/group_list/group_list_screen.dart
- lib/group/presentation/group_list_item.dart
> [refactor] 공통앱바, 그룹 목록, 그룹생성 UI 수정

- lib/auth/domain/usecase/get_current_user_use_case.dart
- lib/auth/module/auth_di.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/core/router/app_router.dart
- 디자인 수정으로 인한 화면 꿀렁임 수정 (로그인, 회원가입)
> [feat] 로그인 기능 오류 수정 

- lib/group/data/data_source/mock_group_data_source_impl.dart
- lib/group/presentation/group_create/group_create_screen_root.dart
- lib/group/presentation/group_setting/group_settings_notifier.dart
- lib/group/presentation/group_timer/group_timer_notifier.dart
- lib/group/presentation/group_timer/group_timer_screen_root.dart
group list 에서 detail view 연결 완료
group 생성 후 setting 들어 갔을 때 성공적으로 data 가져옴.
> [fix] group detail view 연결 및 group setting data 성공적으로 반환

- lib/group/presentation/group_timer/components/member_grid.dart
- lib/group/presentation/group_timer/components/member_skeleton.dart
- lib/group/presentation/group_timer/components/member_timer_item.dart
- timer 활동중 멤버 한줄당 세명으로 변경
- 이용자별 타이머 위치를 바꿨습니다~
- 참고사항/의논사항:
> [feat]: timer 활동중 멤버 한줄당 세명으로 변경

- lib/auth/core/utils/auth_error_messages.dart
- lib/auth/core/utils/auth_exception_mapper.dart
- lib/auth/data/data_source/mock_auth_data_source.dart
- lib/auth/data/repository_impl/auth_repository_impl.dart
- lib/auth/presentation/forgot_password/forgot_password_notifier.dart
- lib/auth/presentation/forgot_password/forgot_password_screen.dart
- lib/auth/presentation/forgot_password/forgot_password_screen_root.dart
- lib/auth/presentation/forgot_password/forgot_password_state.dart
- lib/auth/presentation/login/login_notifier.dart
- lib/auth/presentation/login/login_screen.dart
- lib/auth/presentation/login/login_screen_root.dart
- lib/auth/presentation/login/login_state.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/auth/presentation/signup/signup_screen_root.dart
- lib/auth/presentation/signup/signup_state.dart
- lib/auth/presentation/terms/terms_notifier.dart
- lib/auth/presentation/terms/terms_screen.dart
- lib/auth/presentation/terms/terms_screen_root.dart
- lib/auth/presentation/terms/terms_state.dart
> [sub_bug]: 로그인 실패 시 에러 메시지 개선_상 (#213)

- lib/community/presentation/community_list/community_list_screen.dart
- lib/core/component/list_skeleton.dart
- lib/core/component/navigation_bar.dart
- lib/core/router/app_router.dart
- lib/group/presentation/group_list/group_list_screen.dart
- lib/group/presentation/group_list_item.dart
- lib/group/presentation/group_setting/group_settings_screen.dart
- lib/home/presentation/home_screen.dart
- 커뮤니티 목록 수정, 그룹 생성/수정 수정, home 화면 돋보기 제거, navBar 프로필영역확대
> [feat] 커뮤니티 목록 수정, 그룹 생성/수정 수정, home 화면 돋보기 제거, navBar 프로필영역확대

- lib/core/router/app_router.dart
- lib/intro/presentation/component/focus_stats_chart.dart
- lib/intro/presentation/component/user_intro.dart
- lib/intro/presentation/intro_screen.dart
- lib/setting/presentation/settings_action.dart
- lib/setting/presentation/settings_screen.dart
- lib/setting/presentation/settings_screen_root.dart
- 프로필 및 설정 디자인 개선
- 관련 이슈: #221
> [refactor] 프로필 및 설정 화면 디자인 개선

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/core/service/notification_service.dart
- lib/group/presentation/group_timer/group_timer_screen_root.dart
- lib/main.dart
- 타이머 실행 중 화면을 벗어나면 경고창
- 타이머 실행 중 앱 백그라운드/종료 상태 시 알림 발생 후 타이머 종료
---
> [feat] 그룹 타이머 인터렉션 변경

- lib/setting/presentation/settings_action.dart
- lib/setting/presentation/settings_notifier.dart
- lib/setting/presentation/settings_screen.dart
- lib/setting/presentation/settings_screen_root.dart
- lib/setting/presentation/settings_state.dart
- 설정화면에 앱 버전 및 스토어 연결 추가
- 관련 이슈: #189
> [feat] 설정화면 앱 버전 및 스토어 연결 추가

- lib/core/service/notification_service.dart
- lib/group/presentation/group_timer/components/timer_display.dart
- lib/group/presentation/group_timer/group_timer_notifier.dart
- lib/group/presentation/group_timer/group_timer_screen_root.dart
- lib/main.dart
- pubspec.yaml
> [fix] 타이머 및 알림 권한 설정 관련 로직 수정

- devtools_options.yaml
- lib/community/presentation/community_list/community_list_screen_root.dart
- lib/community/presentation/community_write/community_write_action.dart
- lib/community/presentation/community_write/community_write_notifier.dart
- lib/community/presentation/community_write/community_write_screen.dart
- lib/community/presentation/community_write/community_write_screen_root.dart
- 게시글 작성 후 작성한 게시글을 리스트 스크린에서 바로 볼 수 있도록 수정
- 관련 이슈: #224
> [feat] 게시글 작성 후 작성한 게시글을 리스트 스크린에서 바로 볼 수 있도록 수정

- lib/auth/data/dto/profile_dto.dart
- lib/auth/data/mapper/member_mapper.dart
- lib/auth/domain/model/member.dart
- lib/edit_intro/data/data_source/user_storage_profile_update.dart
- lib/edit_intro/data/repository_impl/edit_intro_repository_impl.dart
- lib/edit_intro/domain/repository/edit_intro_repository.dart
- lib/edit_intro/domain/usecase/update_profile_usecase.dart
- lib/edit_intro/presentation/edit_intro_action.dart
- lib/edit_intro/presentation/edit_intro_notifier.dart
- lib/edit_intro/presentation/screens/edit_intro_root.dart
- lib/edit_intro/presentation/screens/edit_intro_screen.dart
- lib/intro/presentation/component/user_intro.dart
- lib/intro/presentation/intro_screen.dart
- 직무, 스킬 칸이 추가되었습니다~
- 로딩 시간이 줄었습니다~
- 참고사항/의논사항:
> [bug]: profile 로딩 시간 수정, 프로필 및 멤버 클래스 항목 추가

- docs/logic/firebase_model.md
- lib/auth/data/dto/joined_group_dto.dart
- lib/auth/data/dto/timer_activity_dto.dart
- lib/auth/data/dto/user_dto.dart
- lib/community/data/dto/post_comment_dto.dart
- lib/community/data/dto/post_dto.dart
- lib/community/data/dto/post_like_dto.dart
- lib/core/utils/firebase_timestamp_converter.dart
- lib/group/data/dto/group_dto.dart
- lib/group/data/dto/group_member_dto.dart
- lib/group/data/dto/group_timer_activity_dto.dart
- firebase DTO 를 위한 진행
- 관련 이슈: #127
> [feat] firebase를 대비한 DTO 신규 생성

- docs/logic/firebase_group_model.md
- docs/logic/firebase_model.md
- docs/logic/firebase_post_model.md
- docs/logic/firebase_user_model.md
- 기존 `firebase_model.md` 파일을 `firebase_user_model.md`, `firebase_group_model.md`, `firebase_post_model.md`로 분리
- 각 도메인별 문서에 컬렉션 구조, 하위 컬렉션, DTO 구조, 예시 쿼리, 구현 최적화 내용 포함
- `firebase_model.md`는 개요 및 공통 최적화 패턴을 다루도록 수정
- Timestamp 변환, N+1 문제 해결, UI 전용 필드, 트랜잭션, 비정규화 등 공통 최적화 전략 추가
- 관련 이슈: #280
> [docs] Firebase 모델 문서 분리 및 구조 개선

- lib/map/data/repository_impl/group_location_repository_impl.dart
- lib/map/module/group_location_di.dart
> [fix] 잘못된 임포트경로 수정

- lib/onboarding/presentation/onboarding_screen.dart
- lib/onboarding/presentation/onboarding_screen_root.dart
> [fix] onboarding 화면 UI 수정

- lib/community/data/data_source/mock_post_data_source_impl.dart
- lib/community/data/data_source/post_data_source.dart
- lib/community/data/data_source/post_firebase_data_source.dart
- lib/community/data/repository_impl/post_repository_impl.dart
- lib/community/domain/repository/post_repository.dart
- lib/community/domain/usecase/delete_post_use_case.dart
- lib/community/domain/usecase/update_post_use_case.dart
- lib/community/module/community_di.dart
- lib/community/presentation/community_detail/community_detail_action.dart
- lib/community/presentation/community_detail/community_detail_notifier.dart
- lib/community/presentation/community_detail/community_detail_screen.dart
- lib/community/presentation/community_detail/community_detail_screen_root.dart
- lib/community/presentation/community_list/community_list_notifier.dart
- lib/community/presentation/community_list/community_list_screen_root.dart
- lib/community/presentation/community_write/community_write_notifier.dart
- lib/community/presentation/community_write/community_write_screen.dart
- lib/community/presentation/community_write/community_write_screen_root.dart
- lib/community/presentation/community_write/community_write_state.dart
- lib/core/event/app_event.dart
> [feat] 게시글 수정 삭제 기능 구현

- analysis_options.yaml
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/core/styles/app_theme.dart
- lib/group/presentation/group_chat/group_chat_screen.dart
- theme 변경 및 formatter 설정
- 참고사항/의논사항:
> [feat]: theme 변경 및 formatter 설정

- lib/ai_assistance/data/data_source/quiz_data_source.dart
- lib/ai_assistance/data/data_source/study_tip_data_source.dart
- lib/ai_assistance/data/repository_impl/quiz_data_repository_impl.dart
- lib/ai_assistance/data/repository_impl/study_tip_repository_impl.dart
- lib/ai_assistance/module/ai_client_di.dart
- lib/ai_assistance/module/vertex_client.dart
- lib/core/styles/app_theme.dart
- fix(ai): vertex ai 에서 firebase ai로 변경
- 참고사항/의논사항:
> [fix] vertex ai 에서 firebase ai로 변경

- lib/auth/module/auth_di.dart
- lib/community/data/data_source/mock_post_data_source_impl.dart
- lib/community/data/data_source/post_data_source.dart
- lib/community/data/data_source/post_firebase_data_source.dart
- lib/community/data/repository_impl/post_repository_impl.dart
- lib/community/domain/usecase/create_comment_use_case.dart
- lib/community/domain/usecase/create_post_use_case.dart
- lib/community/domain/usecase/delete_post_use_case.dart
- lib/community/domain/usecase/toggle_bookmark_use_case.dart
- lib/community/domain/usecase/toggle_comment_like_use_case.dart
- lib/community/domain/usecase/toggle_like_use_case.dart
- lib/community/domain/usecase/update_post_use_case.dart
- lib/community/module/community_di.dart
- lib/community/presentation/community_write/community_write_notifier.dart
- lib/core/firebase/firebase_providers.dart
- repo의 ref 의존성 제거
- 모든 사용자 인증과 userId 참조는 data source 레이어에서 모두 처리하도록 수정
> [refactor] post 쪽 인증 내부 로직 수정

- lib/community/domain/usecase/search_posts_use_case.dart
- 제목과 내용에 검색한 키워드가 2개 이상 일때 중복된 리스트로 나오는 오류 해결
- 관련 이슈: #312
> [fix] 검색시 중복된 게시글 제거

- lib/home/domain/usecase/get_popular_posts_use_case.dart
- lib/home/module/home_di.dart
- lib/home/presentation/component/popular_post_section.dart
홈화면 인기게시글 실제 데이터로 변경 및 UI 수정
- 관련 이슈: #309
> [feat] 홈화면 인기게시글 실제 데이터로 변경 및 UI 수정

- lib/group/data/data_source/group_data_source.dart
- lib/group/data/data_source/group_firebase_data_source.dart
- lib/group/data/data_source/mock_group_data_source_impl.dart
- lib/group/data/repository_impl/group_repository_impl.dart
- lib/group/module/group_di.dart
1. **GroupDataSource 인터페이스 개선** - 사용자 정보 파라미터 제거
2. **GroupFirebaseDataSource 개선** - Firebase 인스턴스 주입 + 캐싱 로직 추가
3. **MockGroupDataSourceImpl 개선** - 인터페이스 맞춤 + 내부 사용자 정보 처리
4. **GroupRepositoryImpl 개선** - Ref 의존성 제거, 순수 DataSource 호출
5. **Group DI 개선** - Firebase 인스턴스 주입 구조
- 관련 이슈: #308
> [refactor] group data 레이어 영역 리팩토링

- lib/community/presentation/community_list/community_list_screen.dart
> [fix] 게시판 목록 필터 전체보기 클릭 오류 해결

- lib/community/presentation/community_search/community_search_notifier.dart
- lib/community/presentation/community_search/community_search_screen.dart
- lib/community/presentation/community_search/community_search_screen_root.dart
- lib/community/presentation/community_search/community_search_state.dart
- lib/core/service/community_search_notifier.dart
- lib/core/service/search_history_item.dart
- lib/core/service/search_history_service.dart
- lib/group/domain/usecase/search_groups_use_case.dart
- lib/group/presentation/group_search/group_search_notifier.dart
> [feat] 게시판, 그룹 최신  검색어 구현

- lib/group/presentation/group_detail/group_detail_notifier.dart
- lib/group/presentation/group_detail/group_detail_screen.dart
- lib/group/presentation/group_detail/group_detail_screen_root.dart
- Root: AsyncValue 상태 분기 처리 및 state 객체 전달
- Screen: state 객체에서 안전하게 데이터 추출하여 순수 UI 구성
- Notifier: 백그라운드 업데이트로 깜빡임 문제 완전 해결
- 관련 이슈: #315 
- 참고사항/의논사항: 순수 UI여야하는 screen 영역에서 직접 상태 관리해서 리빌드된 문제였음
> [fix] 그룹타이머 깜빡임 이슈 해결

- lib/community/presentation/community_detail/community_detail_screen_root.dart
- lib/community/presentation/community_list/community_list_notifier.dart
- lib/community/presentation/community_list/community_list_screen_root.dart
> [fix] 게시글 삭제 무한 로딩 해결

- lib/group/presentation/group_setting/group_settings_notifier.dart
- lib/group/presentation/group_setting/group_settings_screen.dart
- lib/group/presentation/group_setting/group_settings_state.dart
> [fix] 그룹세팅에서 멤버정보 가져오기

- lib/group/data/data_source/group_firebase_data_source.dart
- lib/group/domain/usecase/leave_group_use_case.dart
- lib/group/presentation/component/group_leave_dialog.dart
- lib/group/presentation/group_setting/group_settings_screen_root.dart
> [fix] 그룹 탈퇴 구현 완료

- lib/community/data/data_source/post_firebase_data_source.dart
- lib/group/data/data_source/group_firebase_data_source.dart
- lib/map/data/data_source/group_location_data_source_impl.dart
- lib/map/data/data_source/map_data_source_impl.dart
- lib/storage/data_source/storage_firebase_data_source.dart
모든 catch 블록 패턴 확인
새 Exception을 생성하는 패턴 식별
스택 트레이스를 캡처하지 않는 코드 식별
리팩토링 진행
각 레이어별로 적절한 예외 처리 가이드라인 정립
데이터 소스 레이어: 원본 예외 rethrow
- 관련 이슈: #272
> [feat] 프로젝트 전체 예외 처리 방식 개선

- ios/Runner/Info.plist
- lib/onboarding/presentation/splash_screen_root.dart
- iOS Info.plist 설정 개선 및 추가, 비동기 함수 사용 패턴 개선
- 관련 이슈: #276 #278
> [feat] iOS Info.plist 설정 개선 및 추가, 비동기 함수 사용 패턴 개선

- lib/group/presentation/group_setting/group_settings_notifier.dart
- lib/group/presentation/group_setting/group_settings_screen.dart
- lib/group/presentation/group_setting/group_settings_screen_root.dart
- lib/group/presentation/group_setting/group_settings_state.dart
- (fix(group): group image storage
- 참고사항/의논사항:
> fix(group): group image storage

- functions/.eslintrc.js
- functions/.gitignore
- functions/index.js
- functions/package-lock.json
- functions/package.json
- lib/auth/data/repository_impl/auth_repository_impl.dart
- lib/auth/domain/repository/auth_repository.dart
- lib/auth/domain/usecase/login_use_case.dart
- lib/auth/module/auth_di.dart
- lib/core/service/app_initialization_service.dart
- lib/main.dart
- lib/notification/data/data_source/mock_notification_data_source_impl.dart
- lib/notification/data/data_source/notification_data_source.dart
- lib/notification/data/data_source/notification_firebase_data_source.dart
- lib/notification/data/repository_impl/notification_repository_impl.dart
- lib/notification/domain/repository/notification_repository.dart
- lib/notification/domain/usecase/delete_notification_use_case.dart
- lib/notification/domain/usecase/mark_notification_as_read_use_case.dart
- lib/notification/module/fcm_di.dart
- lib/notification/module/notification_di.dart
- lib/notification/presentation/notification_notifier.dart
- lib/notification/service/fcm_service.dart
- lib/notification/service/fcm_token_service.dart
- test/notification/data/repository_impl/notification_repository_impl_test.dart
- test/notification/data/repository_impl/notification_repository_impl_test.mocks.dart
- test/notification/domain/usecase/get_notifications_use_case_test.mocks.dart
firebase functions 를 사용해 fcm 및 notification database 저장 구현 완료
firebase 를 사용한 data fetch 완료
> [feat] fcm 연동 및 notification firebase 연결

- lib/group/presentation/group_attendance/attendance_action.dart
- lib/group/presentation/group_attendance/attendance_notifier.dart
- lib/group/presentation/group_attendance/attendance_screen.dart
- lib/group/presentation/group_attendance/attendance_screen_root.dart
- lib/group/presentation/group_attendance/attendance_state.dart
> [fix] 출석부 UI 변경 및 버그수정

- .gitignore
- lib/auth/data/repository_impl/auth_repository_impl.dart
- lib/notification/presentation/notification_notifier.dart
- lib/notification/presentation/notification_screen_root.dart
> [feat] notification navigate 수정 완료

- lib/auth/data/data_source/auth_firebase_data_source.dart
- lib/auth/module/auth_di.dart
- lib/auth/presentation/signup/signup_notifier.dart
- lib/auth/presentation/signup/signup_screen.dart
- lib/auth/presentation/signup/signup_screen_root.dart
1. 닉네임 10자 초과 입력 시 에러텍스트 제대로 출력
2. 이미 사용중인 이메일인 경우 스낵바 두번 나오는거 한번으로 수정
3. auth_di에 ref 수정
4. 회원가입 후 자동 로그인 실행 및 홈화면 이동
5. sign up screen에서 약관동의 왼쪽 체크박스 제거
6. 약관동의하지 않고 회원가입했을때 나타나는 에러텍스트 약관 동의시 제거
- 관련 이슈: #374 #375
> [feat] 회원가입화면 에러 수정 및 리팩토링

- lib/group/presentation/group_chat/group_chat_action.dart
- lib/group/presentation/group_chat/group_chat_notifier.dart
- lib/group/presentation/group_chat/group_chat_screen.dart
- lib/group/presentation/group_chat/group_chat_state.dart
- lib/profile/presentation/component/focus_stats_chart.dart
- lib/profile/presentation/profile_notifier.dart
- fix: 프로필차트 기록 없어도 반환, 그룹채팅 내 사용자 검색기능
- 참고사항/의논사항:
> fix: 프로필차트 기록 없어도 반환, 그룹채팅 내 사용자 검색기능

- lib/auth/data/data_source/mock_auth_data_source.dart
- lib/auth/data/dto/timer_activity_dto.dart
- lib/core/utils/focus_stats_calculator.dart
- lib/group/data/data_source/group_firebase_data_source.dart
- lib/group/data/data_source/mock_group_data_source_impl.dart
- lib/group/data/dto/group_timer_activity_dto.dart
- lib/group/data/mapper/group_member_mapper.dart
- lib/group/domain/model/attendance.dart
- lib/group/presentation/group_attendance/attendance_screen.dart
- lib/group/presentation/group_attendance/attendance_screen_root.dart
- lib/group/presentation/group_create/group_create_action.dart
- lib/group/presentation/group_create/group_create_notifier.dart
- lib/map/data/data_source/group_location_data_source.dart
- lib/map/data/data_source/group_location_data_source_impl.dart
- lib/map/data/data_source/mock_group_location_data_source.dart
- lib/map/data/dto/group_member_location_dto.dart
- lib/map/data/mapper/group_member_location_dto_mapper.dart
- lib/map/data/repository_impl/group_location_repository_impl.dart
- lib/map/domain/model/group_member_location.dart
- lib/map/domain/repository/group_location_repository.dart
- lib/map/domain/usecase/update_member_location_use_case.dart
- lib/map/presentation/group_map_action.dart
- lib/map/presentation/group_map_notifier.dart
- lib/map/presentation/group_map_screen.dart
- lib/map/presentation/group_map_screen_root.dart
- memberId 필드를 userId로 변경
- 관련 이슈: #401
> [refactor] memberId 필드를 userId로 변경

- lib/ai_assistance/module/bot_constants.dart
- lib/ai_assistance/module/group_chat_bot_service.dart
- lib/ai_assistance/module/vertex_client.dart
- lib/group/data/data_source/group_chat_firebase_data_source.dart
- lib/group/data/repository_impl/group_chat_repository_impl.dart
- lib/group/domain/repository/group_chat_repository.dart
- lib/group/domain/usecase/send_bot_use_case.dart
- lib/group/module/group_di.dart
- lib/group/presentation/group_chat/components/chat_bubble.dart
- lib/group/presentation/group_chat/components/chat_input.dart
- lib/group/presentation/group_chat/group_chat_action.dart
- lib/group/presentation/group_chat/group_chat_notifier.dart
- lib/group/presentation/group_chat/group_chat_screen.dart
- lib/group/presentation/group_chat/group_chat_state.dart
> feat(ai): 챗봇

- lib/group/presentation/group_list/components/sort_options_drop_down.dart
- lib/group/presentation/group_list/group_list_action.dart
- lib/group/presentation/group_list/group_list_notifier.dart
- lib/group/presentation/group_list/group_list_screen.dart
- lib/group/presentation/group_list/group_list_screen_root.dart
- lib/group/presentation/group_list/group_list_state.dart
- lib/group/presentation/group_list/group_sort_type.dart
> feat: 정렬 필터 생성

- functions/index.js
1. 프로필 정보 변경 또는 탈퇴 시 동기화 처리 구현 완료
2. 그룹 삭제 또는 그룹 정보 변경 시 동기화 처리 구현 완료
> [feat] firebase functions 기능 추가 완료

- lib/ai_assistance/module/ai_client_di.dart
- lib/ai_assistance/module/vertex_client.dart
- lib/ai_assistance/presentation/quiz_banner.dart
- lib/ai_assistance/presentation/study_tip_banner.dart
- lib/home/presentation/home_screen.dart
- lib/home/presentation/home_screen_root.dart
feat: 홈화면 성능 최적화 및 AI 서비스 사용자 경험 개선
🔧 배경 배너 자동재생 최적화
- 다이얼로그 표시 중 CarouselSlider 일시정지로 리소스 절약
- 앱 생명주기 감지하여 백그라운드에서도 자동재생 중지
- 안전한 상태 복구로 모든 다이얼로그 종료 시 자동재생 재개
🚀 AI 캐시 메커니즘 개선  
- freshStudyTipProvider로 "새 꿀팁!" 기능에서 실제 새 콘텐츠 보장
- 타임스탬프+마이크로초 조합으로 100% 고유 요청 생성
- CacheCleanupService로 자동 캐시 정리 (1시간 기준, 최대 15개)
⚡ AI 클라이언트 사전 초기화
- 홈화면 진입 시 백그라운드에서 Firebase AI 클라이언트 초기화
- 첫 AI 기능 사용 지연 제거 (3-5초 → 즉시 응답)
- 스마트 상태 관리로 중복 초기화 방지
- CPU 사용량 감소 (불필요한 setState 제거)
- 메모리 효율성 향상 (자동 캐시 정리)
- 사용자 대기 시간 제거 (AI 사전 초기화)
- 실제 새 콘텐츠 제공 (캐시 우회 시스템)
Resolves: 배경 리소스 낭비, 캐시 중복, AI 초기화 지연
> feat: 홈화면 성능 최적화 및 AI 서비스 사용자 경험 개선

- lib/group/data/data_source/firebase/group_stats_firebase.dart
- lib/group/data/data_source/group_firebase_data_source.dart
- lib/group/data/dto/group_chat_message_dto.dart
- lib/group/data/dto/group_dto.dart
- lib/group/data/dto/group_member_dto.dart
- lib/group/data/dto/group_timer_activity_dto.dart
- lib/group/data/mapper/group_chat_message_mapper.dart
- lib/group/data/mapper/group_mapper.dart
- lib/group/data/mapper/group_member_mapper.dart
- lib/group/domain/model/chat_message.dart
- lib/group/domain/model/group.dart
- lib/group/domain/model/group_member.dart
- lib/group/domain/model/timer_activity_type.dart
- lib/group/domain/usecase/mock_get_group_detail_use_case.dart
- lib/group/domain/usecase/record_timer_activity_use_case.dart
- lib/group/presentation/group_chat/group_chat_screen.dart
- lib/group/presentation/group_create/group_create_action.dart
- lib/group/presentation/group_create/group_create_notifier.dart
- lib/group/presentation/group_create/group_create_state.dart
- lib/group/presentation/group_detail/components/member_grid.dart
- lib/group/presentation/group_detail/group_detail_screen.dart
- lib/group/presentation/group_setting/group_settings_notifier.dart
> refactor: dto 대격변

- lib/group/presentation/group_detail/components/member_grid.dart
- lib/group/presentation/group_detail/components/timer_display.dart
- lib/group/presentation/group_detail/group_detail_screen.dart
> [bug] 타이머 상세 UI 이슈 해결 (00:00:00, 2배차이나는 타이머)

- lib/core/component/gradient_app_bar.dart
- lib/core/component/nav_bar/navigation_bar.dart
- lib/group/presentation/group_detail/group_detail_screen_root.dart
- 앱바 오버플로 수정
- 그룹화면 ref 에러 수정
- 네비게이션바 클릭영역 확장
- 관련 이슈: #448
> [feat] (1) 앱바 오버플로 수정 (2) 그룹화면 ref 에러 수정 (3) 네비게이션바 클릭영역 확장

- lib/group/data/data_source/firebase/group_timer_firebase.dart
- 그룹 타이머 일시정지 시 만료 시간 설정
- 그룹 문서에서 `pauseTimeLimit`(분 단위) 필드 값을 읽어와 만료 시간 계산
- 기본값은 120분으로 설정
- `pauseExpiryTime` 필드를 `Timestamp` 타입으로 활동 문서에 저장
- 타이머 재개 시 일시정지 만료 시간 확인
- 현재 시간이 만료 시간을 초과한 경우, 타이머 상태를 'end'로 변경
- 만료되지 않은 경우, 정상적으로 타이머 재개
- 불필요한 `userName` 파라미터 제거
> feat(group_timer): 그룹 타이머 일시정지 만료 기능 추가

- functions/index.js
- 사용자 통계 업데이트 로직 제거
- `processAttendanceRecords` 함수 추가:
- 매일 새벽 1시 그룹별 어제 활동 멤버 출석부 집계
- 그룹별 `monthlyStats` 컬렉션에 `YYYY-MM` 문서로 저장
- 각 문서 내에 `YYYY-MM-DD` 필드로 멤버 ID와 활동 시간(분) 기록
- `cleanupUserData` 함수 개선:
- 사용자 삭제 시 `timerActivities` 대신 `summary` 컬렉션 삭제
- FCM 토큰 삭제 로직에 부모 문서 삭제 추가
- `cleanupGroupData` 함수 개선:
- 그룹 삭제 시 `timerActivities` 대신 `monthlyStats` 컬렉션 삭제
- `joingroup` 업데이트 시 `group_id` 기준으로 필터링하여 정확도 향상
- `syncProfileChanges` 함수 개선:
- 사용자 프로필 변경 시 관련 데이터 동기화
- 그룹 타이머 활동 정보 업데이트 로직 제거
- `syncGroupChanges` 함수 개선:
- 그룹 정보 변경 시 멤버의 `joingroup` 업데이트 방식 변경 (더 정확한 업데이트)
- 관련 이슈: #461
> [refactor] Cloud Functions 로직 개선 및 통합

- lib/ai_assistance/data/repository_impl/quiz_data_repository_impl.dart
- lib/ai_assistance/domain/model/skill_selector.dart
- lib/ai_assistance/module/quiz_prompt.dart
- lib/profile/presentation/user_profile/user_profile_screen.dart
- json 파싱 오류에 따른 프롬프트 개선
- 참고사항/의논사항:
> fix: json 파싱 오류에 따른 프롬프트 개선, 다른사람 프로필 카드 확인시 활동중 표시 개선

- lib/home/presentation/home_notifier.dart
- lib/home/presentation/home_screen.dart
- lib/home/presentation/home_screen_root.dart
- lib/home/presentation/home_state.dart
- lib/notification/presentation/notification_screen.dart
Home Appbar notification 버튼 read unread 상태 (빨간점) 처리 완료
notification 화면에서 unread 알림이 있을 경우 appbar 우측에 done_all icon 표시, 눌렀을 경우 모든 알림 읽음 처리 완료
알림이 다 읽어져 있을경우는 숨겨짐.
> [fix] Home Appbar notification 버튼 상태 처리 및 알림 모두 읽음 처리

- lib/main.dart
- 다크모드 테마를 라이트모드 테마로 변경
- 테마 모드를 시스템 설정이 아닌 라이트모드로 고정
> [fix] : 다크모드 비활성화
